using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DevExpress.XtraEditors;
using NhuaNong.Data;
using NhuaNong.Utils;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace NhuaNong.MasterData
{
  public partial class NewCongTruongView
  {
    private IContainer components;
    private PanelControl pnlMain;
    private LabelControl labelControl1;
    private CheckEdit chkActive;
    private TextEdit txtPhone;
    private TextEdit txtDiaChi;
    private TextEdit txtTenCongTruong;
    private TextEdit txtMaCongTruong;
    private LabelControl lblPhone;
    private LabelControl lblAddress;
    private LabelControl lblTenCongTruong;
    private LabelControl lblMaCongTruong;
    private PanelControl pnlCommand;
    private SimpleButton btnClose;
    private SimpleButton btnSave;
    private SimpleButton btnSaveNew;

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      this.pnlMain = new PanelControl();
      this.pnlCommand = new PanelControl();
      this.btnClose = new SimpleButton();
      this.btnSave = new SimpleButton();
      this.btnSaveNew = new SimpleButton();
      this.labelControl1 = new LabelControl();
      this.chkActive = new CheckEdit();
      this.txtPhone = new TextEdit();
      this.txtDiaChi = new TextEdit();
      this.txtTenCongTruong = new TextEdit();
      this.txtMaCongTruong = new TextEdit();
      this.lblPhone = new LabelControl();
      this.lblAddress = new LabelControl();
      this.lblTenCongTruong = new LabelControl();
      this.lblMaCongTruong = new LabelControl();
      this.pnlMain.BeginInit();
      this.pnlMain.SuspendLayout();
      this.pnlCommand.BeginInit();
      this.pnlCommand.SuspendLayout();
      this.chkActive.Properties.BeginInit();
      this.txtPhone.Properties.BeginInit();
      this.txtDiaChi.Properties.BeginInit();
      this.txtTenCongTruong.Properties.BeginInit();
      this.txtMaCongTruong.Properties.BeginInit();
      this.SuspendLayout();
      this.pnlMain.Controls.Add((Control)this.pnlCommand);
      this.pnlMain.Controls.Add((Control)this.labelControl1);
      this.pnlMain.Controls.Add((Control)this.chkActive);
      this.pnlMain.Controls.Add((Control)this.txtPhone);
      this.pnlMain.Controls.Add((Control)this.txtDiaChi);
      this.pnlMain.Controls.Add((Control)this.txtTenCongTruong);
      this.pnlMain.Controls.Add((Control)this.txtMaCongTruong);
      this.pnlMain.Controls.Add((Control)this.lblPhone);
      this.pnlMain.Controls.Add((Control)this.lblAddress);
      this.pnlMain.Controls.Add((Control)this.lblTenCongTruong);
      this.pnlMain.Controls.Add((Control)this.lblMaCongTruong);
      this.pnlMain.Dock = DockStyle.Fill;
      this.pnlMain.Location = new Point(0, 0);
      this.pnlMain.Margin = new Padding(2);
      this.pnlMain.Name = "pnlMain";
      this.pnlMain.Size = new Size(495, 245);
      this.pnlMain.TabIndex = 1;
      this.pnlCommand.Controls.Add((Control)this.btnClose);
      this.pnlCommand.Controls.Add((Control)this.btnSave);
      this.pnlCommand.Controls.Add((Control)this.btnSaveNew);
      this.pnlCommand.Dock = DockStyle.Bottom;
      this.pnlCommand.Location = new Point(2, 198);
      this.pnlCommand.Margin = new Padding(2);
      this.pnlCommand.Name = "pnlCommand";
      this.pnlCommand.Size = new Size(491, 45);
      this.pnlCommand.TabIndex = 14;
      this.btnClose.Appearance.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte)0);
      this.btnClose.Appearance.Options.UseFont = true;
      this.btnClose.Location = new Point(312, 9);
      this.btnClose.Margin = new Padding(2);
      this.btnClose.Name = "btnClose";
      this.btnClose.Size = new Size(98, 30);
      this.btnClose.TabIndex = 2;
      this.btnClose.Text = "Đóng";
      this.btnClose.Click += new EventHandler(this.btnClose_Click);
      this.btnSave.Appearance.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte)0);
      this.btnSave.Appearance.Options.UseFont = true;
      this.btnSave.Location = new Point(207, 9);
      this.btnSave.Margin = new Padding(2);
      this.btnSave.Name = "btnSave";
      this.btnSave.Size = new Size(98, 30);
      this.btnSave.TabIndex = 1;
      this.btnSave.Text = "Lưu";
      this.btnSave.Click += new EventHandler(this.btnSave_Click);
      this.btnSaveNew.Appearance.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte)0);
      this.btnSaveNew.Appearance.Options.UseFont = true;
      this.btnSaveNew.Location = new Point(74, 9);
      this.btnSaveNew.Margin = new Padding(2);
      this.btnSaveNew.Name = "btnSaveNew";
      this.btnSaveNew.Size = new Size(126, 30);
      this.btnSaveNew.TabIndex = 0;
      this.btnSaveNew.Text = "Lưu và Thêm Mới";
      this.btnSaveNew.Click += new EventHandler(this.btnSaveNew_Click);
      this.labelControl1.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte)0);
      this.labelControl1.Appearance.Options.UseFont = true;
      this.labelControl1.Location = new Point(85, 162);
      this.labelControl1.Margin = new Padding(2);
      this.labelControl1.Name = "labelControl1";
      this.labelControl1.Size = new Size(54, 16);
      this.labelControl1.TabIndex = 13;
      this.labelControl1.Text = "Kích hoạt";
      this.labelControl1.Visible = false;
      this.chkActive.Location = new Point(200, 160);
      this.chkActive.Margin = new Padding(2);
      this.chkActive.Name = "chkActive";
      this.chkActive.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte)0);
      this.chkActive.Properties.Appearance.Options.UseFont = true;
      this.chkActive.Properties.Caption = "";
      this.chkActive.Size = new Size(92, 20);
      this.chkActive.TabIndex = 12;
      this.chkActive.Visible = false;
      this.txtPhone.Location = new Point(200, 130);
      this.txtPhone.Margin = new Padding(2);
      this.txtPhone.Name = "txtPhone";
      this.txtPhone.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte)0);
      this.txtPhone.Properties.Appearance.Options.UseFont = true;
      this.txtPhone.Size = new Size(200, 22);
      this.txtPhone.TabIndex = 10;
      this.txtDiaChi.Location = new Point(200, 100);
      this.txtDiaChi.Margin = new Padding(2);
      this.txtDiaChi.Name = "txtDiaChi";
      this.txtDiaChi.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte)0);
      this.txtDiaChi.Properties.Appearance.Options.UseFont = true;
      this.txtDiaChi.Size = new Size(200, 22);
      this.txtDiaChi.TabIndex = 9;
      this.txtTenCongTruong.Location = new Point(200, 70);
      this.txtTenCongTruong.Margin = new Padding(2);
      this.txtTenCongTruong.Name = "txtTenCongTruong";
      this.txtTenCongTruong.Properties.Appearance.BackColor = Color.White;
      this.txtTenCongTruong.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte)0);
      this.txtTenCongTruong.Properties.Appearance.Options.UseBackColor = true;
      this.txtTenCongTruong.Properties.Appearance.Options.UseFont = true;
      this.txtTenCongTruong.Size = new Size(200, 22);
      this.txtTenCongTruong.TabIndex = 8;
      this.txtMaCongTruong.Location = new Point(200, 40);
      this.txtMaCongTruong.Margin = new Padding(2);
      this.txtMaCongTruong.Name = "txtMaCongTruong";
      this.txtMaCongTruong.Properties.Appearance.BackColor = Color.FromArgb(220, 233, 252);
      this.txtMaCongTruong.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte)0);
      this.txtMaCongTruong.Properties.Appearance.Options.UseBackColor = true;
      this.txtMaCongTruong.Properties.Appearance.Options.UseFont = true;
      this.txtMaCongTruong.Properties.ReadOnly = true;
      this.txtMaCongTruong.Size = new Size(200, 22);
      this.txtMaCongTruong.TabIndex = 6;
      this.lblPhone.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte)0);
      this.lblPhone.Appearance.Options.UseFont = true;
      this.lblPhone.Location = new Point(85, 133);
      this.lblPhone.Margin = new Padding(2);
      this.lblPhone.Name = "lblPhone";
      this.lblPhone.Size = new Size(39, 16);
      this.lblPhone.TabIndex = 3;
      this.lblPhone.Text = "Phone";
      this.lblAddress.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte)0);
      this.lblAddress.Appearance.Options.UseFont = true;
      this.lblAddress.Location = new Point(85, 103);
      this.lblAddress.Margin = new Padding(2);
      this.lblAddress.Name = "lblAddress";
      this.lblAddress.Size = new Size(40, 16);
      this.lblAddress.TabIndex = 2;
      this.lblAddress.Text = "Địa chỉ";
      this.lblTenCongTruong.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte)0);
      this.lblTenCongTruong.Appearance.Options.UseFont = true;
      this.lblTenCongTruong.Location = new Point(85, 73);
      this.lblTenCongTruong.Margin = new Padding(2);
      this.lblTenCongTruong.Name = "lblTenCongTruong";
      this.lblTenCongTruong.Size = new Size(97, 16);
      this.lblTenCongTruong.TabIndex = 1;
      this.lblTenCongTruong.Text = "Tên công trường";
      this.lblMaCongTruong.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte)0);
      this.lblMaCongTruong.Appearance.Options.UseFont = true;
      this.lblMaCongTruong.Location = new Point(85, 43);
      this.lblMaCongTruong.Margin = new Padding(2);
      this.lblMaCongTruong.Name = "lblMaCongTruong";
      this.lblMaCongTruong.Size = new Size(92, 16);
      this.lblMaCongTruong.TabIndex = 0;
      this.lblMaCongTruong.Text = "Mã công trường";
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.Controls.Add((Control)this.pnlMain);
      this.Name = "NewCongTruongView";
      this.Size = new Size(495, 245);
      this.pnlMain.EndInit();
      this.pnlMain.ResumeLayout(false);
      this.pnlMain.PerformLayout();
      this.pnlCommand.EndInit();
      this.pnlCommand.ResumeLayout(false);
      this.chkActive.Properties.EndInit();
      this.txtPhone.Properties.EndInit();
      this.txtDiaChi.Properties.EndInit();
      this.txtTenCongTruong.Properties.EndInit();
      this.txtMaCongTruong.Properties.EndInit();
      this.ResumeLayout(false);
    }
  }
}
