using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DevExpress.Utils;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace NhuaNong.MasterData
{
  public partial class UcBaseSilo2
  {
    private IContainer components;
    protected PictureEdit picBackground;
    protected LabelControl lblCaption;
    protected LabelControl lblDesc;
    protected SpinEdit spn0;
    protected SpinEdit spn1;
    protected SpinEdit spn2;
    protected SpinEdit spn3;
    public LabelControl labelControl1;
    private PictureEdit pictureEdit1;
    private PictureEdit pictureEdit2;
    private PictureEdit pictureEdit3;
    private PictureEdit pictureEdit4;
    private PictureEdit pictureEdit5;
    private PictureEdit pictureEdit6;

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      this.picBackground = new PictureEdit();
      this.lblCaption = new LabelControl();
      this.lblDesc = new LabelControl();
      this.spn0 = new SpinEdit();
      this.spn1 = new SpinEdit();
      this.spn2 = new SpinEdit();
      this.spn3 = new SpinEdit();
      this.labelControl1 = new LabelControl();
      this.pictureEdit1 = new PictureEdit();
      this.pictureEdit2 = new PictureEdit();
      this.pictureEdit3 = new PictureEdit();
      this.pictureEdit4 = new PictureEdit();
      this.pictureEdit5 = new PictureEdit();
      this.pictureEdit6 = new PictureEdit();
      this.picBackground.Properties.BeginInit();
      this.spn0.Properties.BeginInit();
      this.spn1.Properties.BeginInit();
      this.spn2.Properties.BeginInit();
      this.spn3.Properties.BeginInit();
      this.pictureEdit1.Properties.BeginInit();
      this.pictureEdit2.Properties.BeginInit();
      this.pictureEdit3.Properties.BeginInit();
      this.pictureEdit4.Properties.BeginInit();
      this.pictureEdit5.Properties.BeginInit();
      this.pictureEdit6.Properties.BeginInit();
      this.SuspendLayout();
      this.picBackground.AllowDrop = true;
      this.picBackground.Dock = DockStyle.Fill;
      this.picBackground.Location = new Point(0, 0);
      this.picBackground.Margin = new Padding(3, 2, 3, 2);
      this.picBackground.Name = "picBackground";
      this.picBackground.Properties.AllowFocused = false;
      this.picBackground.Properties.Appearance.BackColor = Color.Maroon;
      this.picBackground.Properties.Appearance.Options.UseBackColor = true;
      this.picBackground.Properties.BorderStyle = BorderStyles.NoBorder;
      this.picBackground.Properties.ShowCameraMenuItem = CameraMenuItemVisibility.Auto;
      this.picBackground.Size = new Size(100, 206);
      this.picBackground.TabIndex = 0;
      this.picBackground.Click += new EventHandler(this.picBackground_Click);
      this.lblCaption.Appearance.BackColor = Color.LimeGreen;
      this.lblCaption.Appearance.Font = new Font("Tahoma", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte)0);
      this.lblCaption.Appearance.ForeColor = SystemColors.Window;
      this.lblCaption.Appearance.Options.UseBackColor = true;
      this.lblCaption.Appearance.Options.UseFont = true;
      this.lblCaption.Appearance.Options.UseForeColor = true;
      this.lblCaption.Appearance.Options.UseTextOptions = true;
      this.lblCaption.Appearance.TextOptions.HAlignment = HorzAlignment.Center;
      this.lblCaption.AutoSizeMode = LabelAutoSizeMode.None;
      this.lblCaption.BorderStyle = BorderStyles.Flat;
      this.lblCaption.Dock = DockStyle.Bottom;
      this.lblCaption.Location = new Point(0, 193);
      this.lblCaption.Name = "lblCaption";
      this.lblCaption.Size = new Size(100, 13);
      this.lblCaption.TabIndex = 3;
      this.lblCaption.Text = "SILO";
      this.lblCaption.Visible = false;
      this.lblCaption.TextChanged += new EventHandler(this.lblCaption_TextChanged);
      this.lblCaption.Click += new EventHandler(this.lblCaption_Click);
      this.lblDesc.Appearance.BackColor = Color.Transparent;
      this.lblDesc.Appearance.Font = new Font("Tahoma", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte)0);
      this.lblDesc.Appearance.ForeColor = Color.White;
      this.lblDesc.Appearance.Options.UseBackColor = true;
      this.lblDesc.Appearance.Options.UseFont = true;
      this.lblDesc.Appearance.Options.UseForeColor = true;
      this.lblDesc.Appearance.Options.UseTextOptions = true;
      this.lblDesc.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
      this.lblDesc.Appearance.TextOptions.VAlignment = VertAlignment.Bottom;
      this.lblDesc.Appearance.TextOptions.WordWrap = WordWrap.Wrap;
      this.lblDesc.AutoSizeMode = LabelAutoSizeMode.None;
      this.lblDesc.Dock = DockStyle.Top;
      this.lblDesc.Location = new Point(0, 0);
      this.lblDesc.Margin = new Padding(3, 2, 3, 2);
      this.lblDesc.Name = "lblDesc";
      this.lblDesc.Size = new Size(100, 20);
      this.lblDesc.TabIndex = 3;
      this.lblDesc.Text = "Diễn Giải";
      this.lblDesc.MouseHover += new EventHandler(this.lblDesc_MouseHover);
      this.spn0.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
      this.spn0.EditValue = (object)new Decimal(new int[4]);
      this.spn0.Location = new Point(3, 38);
      this.spn0.Name = "spn0";
      this.spn0.Properties.Appearance.BackColor = Color.Black;
      this.spn0.Properties.Appearance.Font = new Font("Tahoma", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte)0);
      this.spn0.Properties.Appearance.ForeColor = Color.White;
      this.spn0.Properties.Appearance.Options.UseBackColor = true;
      this.spn0.Properties.Appearance.Options.UseFont = true;
      this.spn0.Properties.Appearance.Options.UseForeColor = true;
      this.spn0.Properties.BorderStyle = BorderStyles.Style3D;
      this.spn0.Properties.DisplayFormat.FormatString = "n2";
      this.spn0.Properties.DisplayFormat.FormatType = FormatType.Numeric;
      this.spn0.Properties.EditFormat.FormatString = "n2";
      this.spn0.Properties.EditFormat.FormatType = FormatType.Numeric;
      this.spn0.Properties.Mask.EditMask = "n2";
      this.spn0.Properties.MaxValue = new Decimal(new int[4]
      {
        99,
        0,
        0,
        0
      });
      this.spn0.Size = new Size(92, 22);
      this.spn0.TabIndex = 3;
      this.spn0.ToolTip = "Độ Ẩm Cát Đá";
      this.spn0.EditValueChanged += new EventHandler(this.spn0_EditValueChanged);
      this.spn1.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
      this.spn1.EditValue = (object)new Decimal(new int[4]);
      this.spn1.Location = new Point(3, 82);
      this.spn1.Margin = new Padding(3, 2, 3, 2);
      this.spn1.Name = "spn1";
      this.spn1.Properties.AllowFocused = false;
      this.spn1.Properties.Appearance.BackColor = Color.Black;
      this.spn1.Properties.Appearance.Font = new Font("Tahoma", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte)0);
      this.spn1.Properties.Appearance.ForeColor = Color.Yellow;
      this.spn1.Properties.Appearance.Options.UseBackColor = true;
      this.spn1.Properties.Appearance.Options.UseFont = true;
      this.spn1.Properties.Appearance.Options.UseForeColor = true;
      this.spn1.Properties.BorderStyle = BorderStyles.Style3D;
      this.spn1.Properties.DisplayFormat.FormatString = "n0";
      this.spn1.Properties.DisplayFormat.FormatType = FormatType.Numeric;
      this.spn1.Properties.EditFormat.FormatString = "n2";
      this.spn1.Properties.EditFormat.FormatType = FormatType.Numeric;
      this.spn1.Properties.Mask.EditMask = "n0";
      this.spn1.Properties.ReadOnly = true;
      this.spn1.Size = new Size(92, 22);
      this.spn1.TabIndex = 4;
      this.spn1.ToolTip = "KL Cài Đặt";
      this.spn1.Click += new EventHandler(this.spn1_Click);
      this.spn2.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
      this.spn2.EditValue = (object)new Decimal(new int[4]);
      this.spn2.Location = new Point(3, 105);
      this.spn2.Margin = new Padding(3, 2, 3, 2);
      this.spn2.Name = "spn2";
      this.spn2.Properties.AllowFocused = false;
      this.spn2.Properties.Appearance.BackColor = Color.Black;
      this.spn2.Properties.Appearance.Font = new Font("Tahoma", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte)0);
      this.spn2.Properties.Appearance.ForeColor = Color.Red;
      this.spn2.Properties.Appearance.Options.UseBackColor = true;
      this.spn2.Properties.Appearance.Options.UseFont = true;
      this.spn2.Properties.Appearance.Options.UseForeColor = true;
      this.spn2.Properties.BorderStyle = BorderStyles.Style3D;
      this.spn2.Properties.DisplayFormat.FormatString = "n0";
      this.spn2.Properties.DisplayFormat.FormatType = FormatType.Numeric;
      this.spn2.Properties.EditFormat.FormatString = "n2";
      this.spn2.Properties.EditFormat.FormatType = FormatType.Numeric;
      this.spn2.Properties.Mask.EditMask = "n0";
      this.spn2.Properties.ReadOnly = true;
      this.spn2.Size = new Size(92, 22);
      this.spn2.TabIndex = 5;
      this.spn2.ToolTip = "KL Cần Cân";
      this.spn2.Click += new EventHandler(this.spn2_Click);
      this.spn3.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
      this.spn3.EditValue = (object)new Decimal(new int[4]);
      this.spn3.Location = new Point(3, (int)sbyte.MaxValue);
      this.spn3.Margin = new Padding(3, 2, 3, 2);
      this.spn3.Name = "spn3";
      this.spn3.Properties.AllowFocused = false;
      this.spn3.Properties.Appearance.BackColor = Color.Black;
      this.spn3.Properties.Appearance.Font = new Font("Tahoma", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte)0);
      this.spn3.Properties.Appearance.ForeColor = Color.Lime;
      this.spn3.Properties.Appearance.Options.UseBackColor = true;
      this.spn3.Properties.Appearance.Options.UseFont = true;
      this.spn3.Properties.Appearance.Options.UseForeColor = true;
      this.spn3.Properties.BorderStyle = BorderStyles.Style3D;
      this.spn3.Properties.DisplayFormat.FormatString = "n0";
      this.spn3.Properties.DisplayFormat.FormatType = FormatType.Numeric;
      this.spn3.Properties.EditFormat.FormatString = "n2";
      this.spn3.Properties.EditFormat.FormatType = FormatType.Numeric;
      this.spn3.Properties.Mask.EditMask = "n0";
      this.spn3.Properties.ReadOnly = true;
      this.spn3.Size = new Size(92, 22);
      this.spn3.TabIndex = 6;
      this.spn3.ToolTip = "KL Thực Tế";
      this.spn3.Click += new EventHandler(this.spn3_Click);
      this.labelControl1.AutoSizeMode = LabelAutoSizeMode.None;
      this.labelControl1.BorderStyle = BorderStyles.NoBorder;
      this.labelControl1.Dock = DockStyle.Top;
      this.labelControl1.Location = new Point(0, 20);
      this.labelControl1.Name = "labelControl1";
      this.labelControl1.Size = new Size(100, 15);
      this.labelControl1.TabIndex = 1;
      this.pictureEdit1.Location = new Point(70, 193);
      this.pictureEdit1.Name = "pictureEdit1";
      this.pictureEdit1.Properties.AllowFocused = false;
      this.pictureEdit1.Properties.Appearance.BackColor = Color.Transparent;
      this.pictureEdit1.Properties.Appearance.Options.UseBackColor = true;
      this.pictureEdit1.Properties.BorderStyle = BorderStyles.NoBorder;
      this.pictureEdit1.Properties.NullText = " ";
      this.pictureEdit1.Properties.ReadOnly = true;
      this.pictureEdit1.Properties.ShowCameraMenuItem = CameraMenuItemVisibility.Auto;
      this.pictureEdit1.Size = new Size(30, 13);
      this.pictureEdit1.TabIndex = 7;
      this.pictureEdit2.Location = new Point(81, 180);
      this.pictureEdit2.Name = "pictureEdit2";
      this.pictureEdit2.Properties.AllowFocused = false;
      this.pictureEdit2.Properties.Appearance.BackColor = Color.Transparent;
      this.pictureEdit2.Properties.Appearance.Options.UseBackColor = true;
      this.pictureEdit2.Properties.BorderStyle = BorderStyles.NoBorder;
      this.pictureEdit2.Properties.NullText = " ";
      this.pictureEdit2.Properties.ReadOnly = true;
      this.pictureEdit2.Properties.ShowCameraMenuItem = CameraMenuItemVisibility.Auto;
      this.pictureEdit2.Size = new Size(20, 13);
      this.pictureEdit2.TabIndex = 8;
      this.pictureEdit3.Location = new Point(0, 193);
      this.pictureEdit3.Name = "pictureEdit3";
      this.pictureEdit3.Properties.AllowFocused = false;
      this.pictureEdit3.Properties.Appearance.BackColor = Color.Transparent;
      this.pictureEdit3.Properties.Appearance.Options.UseBackColor = true;
      this.pictureEdit3.Properties.BorderStyle = BorderStyles.NoBorder;
      this.pictureEdit3.Properties.NullText = " ";
      this.pictureEdit3.Properties.ReadOnly = true;
      this.pictureEdit3.Properties.ShowCameraMenuItem = CameraMenuItemVisibility.Auto;
      this.pictureEdit3.Size = new Size(24, 13);
      this.pictureEdit3.TabIndex = 9;
      this.pictureEdit4.Location = new Point(0, 180);
      this.pictureEdit4.Name = "pictureEdit4";
      this.pictureEdit4.Properties.AllowFocused = false;
      this.pictureEdit4.Properties.Appearance.BackColor = Color.Transparent;
      this.pictureEdit4.Properties.Appearance.Options.UseBackColor = true;
      this.pictureEdit4.Properties.BorderStyle = BorderStyles.NoBorder;
      this.pictureEdit4.Properties.NullText = " ";
      this.pictureEdit4.Properties.ReadOnly = true;
      this.pictureEdit4.Properties.ShowCameraMenuItem = CameraMenuItemVisibility.Auto;
      this.pictureEdit4.Size = new Size(14, 13);
      this.pictureEdit4.TabIndex = 10;
      this.pictureEdit5.Location = new Point(0, 167);
      this.pictureEdit5.Name = "pictureEdit5";
      this.pictureEdit5.Properties.AllowFocused = false;
      this.pictureEdit5.Properties.Appearance.BackColor = Color.Transparent;
      this.pictureEdit5.Properties.Appearance.Options.UseBackColor = true;
      this.pictureEdit5.Properties.BorderStyle = BorderStyles.NoBorder;
      this.pictureEdit5.Properties.NullText = " ";
      this.pictureEdit5.Properties.ReadOnly = true;
      this.pictureEdit5.Properties.ShowCameraMenuItem = CameraMenuItemVisibility.Auto;
      this.pictureEdit5.Size = new Size(6, 13);
      this.pictureEdit5.TabIndex = 11;
      this.pictureEdit6.Location = new Point(91, 167);
      this.pictureEdit6.Name = "pictureEdit6";
      this.pictureEdit6.Properties.AllowFocused = false;
      this.pictureEdit6.Properties.Appearance.BackColor = Color.Transparent;
      this.pictureEdit6.Properties.Appearance.Options.UseBackColor = true;
      this.pictureEdit6.Properties.BorderStyle = BorderStyles.NoBorder;
      this.pictureEdit6.Properties.NullText = " ";
      this.pictureEdit6.Properties.ReadOnly = true;
      this.pictureEdit6.Properties.ShowCameraMenuItem = CameraMenuItemVisibility.Auto;
      this.pictureEdit6.Size = new Size(10, 13);
      this.pictureEdit6.TabIndex = 12;
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.Controls.Add((Control)this.pictureEdit6);
      this.Controls.Add((Control)this.pictureEdit5);
      this.Controls.Add((Control)this.pictureEdit4);
      this.Controls.Add((Control)this.pictureEdit3);
      this.Controls.Add((Control)this.pictureEdit2);
      this.Controls.Add((Control)this.pictureEdit1);
      this.Controls.Add((Control)this.labelControl1);
      this.Controls.Add((Control)this.spn3);
      this.Controls.Add((Control)this.spn2);
      this.Controls.Add((Control)this.spn1);
      this.Controls.Add((Control)this.spn0);
      this.Controls.Add((Control)this.lblDesc);
      this.Controls.Add((Control)this.lblCaption);
      this.Controls.Add((Control)this.picBackground);
      this.Margin = new Padding(3, 2, 3, 2);
      this.Name = "UcBaseSilo2";
      this.Size = new Size(100, 206);
      this.picBackground.Properties.EndInit();
      this.spn0.Properties.EndInit();
      this.spn1.Properties.EndInit();
      this.spn2.Properties.EndInit();
      this.spn3.Properties.EndInit();
      this.pictureEdit1.Properties.EndInit();
      this.pictureEdit2.Properties.EndInit();
      this.pictureEdit3.Properties.EndInit();
      this.pictureEdit4.Properties.EndInit();
      this.pictureEdit5.Properties.EndInit();
      this.pictureEdit6.Properties.EndInit();
      this.ResumeLayout(false);
    }
  }
}
